"""Build the public, editable SVG figures from tracked result tables.

No manuscript, network service, hosted model, or third-party Python package is
needed. Run ``python3 scripts/visualise/build_release_figures.py`` from anywhere.
Use ``--check`` to compare generated bytes with the checked-in release assets.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from html import escape
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "figures"
R1 = Path("analysis/metrics/r1/network_metrics_table.csv")
R2 = Path("analysis/metrics/r2/network_metrics_table.csv")
BOOT = Path("analysis/metrics/neurips26/bootstrap_argument_differences.csv")

INK = "#F3F7FF"
MUTED = "#B5C3D8"
NAVY = "#0B1220"
PANEL = "#152239"
CYAN = "#34D3E6"
GREEN = "#56D3A3"
AMBER = "#F9C66B"
STROKE = "#38516E"


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def text(x: float, y: float, value: str, size: int = 18, color: str = INK,
         weight: int = 400, anchor: str = "start") -> str:
    return (f'<text x="{x:g}" y="{y:g}" fill="{color}" font-size="{size}" '
            f'font-weight="{weight}" text-anchor="{anchor}" '
            f'font-family="Arial, Helvetica, sans-serif">{escape(value)}</text>')


def rect(x: float, y: float, w: float, h: float, fill: str, radius: int = 0,
         stroke: str = "none", sw: int = 1) -> str:
    return (f'<rect x="{x:g}" y="{y:g}" width="{w:g}" height="{h:g}" '
            f'rx="{radius}" fill="{fill}" stroke="{stroke}" stroke-width="{sw}"/>')


def line(x1: float, y1: float, x2: float, y2: float, color: str = STROKE,
         sw: int = 2, extra: str = "") -> str:
    return (f'<line x1="{x1:g}" y1="{y1:g}" x2="{x2:g}" y2="{y2:g}" '
            f'stroke="{color}" stroke-width="{sw}" {extra}/>')


def svg(w: int, h: int, title: str, desc: str, elements: list[str]) -> str:
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
            f'viewBox="0 0 {w} {h}" role="img" aria-labelledby="title desc">\n'
            f'<title id="title">{escape(title)}</title>\n'
            f'<desc id="desc">{escape(desc)}</desc>\n'
            + "\n".join(elements) + "\n</svg>\n")


def icon_document(x: int, y: int, color: str) -> str:
    return (f'<path d="M{x} {y}h24l8 8v35h-32z M{x+24} {y}v8h8" '
            f'fill="none" stroke="{color}" stroke-width="2.5"/>'
            + line(x+6, y+18, x+25, y+18, color, 2)
            + line(x+6, y+25, x+25, y+25, color, 2))


def icon_review(x: int, y: int, color: str) -> str:
    return (f'<circle cx="{x+16}" cy="{y+17}" r="13" fill="none" '
            f'stroke="{color}" stroke-width="2.5"/>'
            + line(x+26, y+27, x+39, y+40, color, 3))


def icon_network(x: int, y: int, color: str) -> str:
    nodes = [(x+6,y+24),(x+25,y+6),(x+43,y+24),(x+25,y+43)]
    out = [line(*nodes[0], *nodes[1], color),line(*nodes[1], *nodes[2], color),
           line(*nodes[2], *nodes[3], color),line(*nodes[3], *nodes[0], color)]
    out += [f'<circle cx="{a}" cy="{b}" r="4.5" fill="{NAVY}" '
            f'stroke="{color}" stroke-width="2"/>' for a,b in nodes]
    return "".join(out)


def icon_table(x: int, y: int, color: str) -> str:
    return (rect(x,y,43,39,"none",4,color,2)
            +line(x,y+13,x+43,y+13,color,2)
            +line(x+21,y+13,x+21,y+39,color,2)
            +line(x,y+26,x+43,y+26,color,2))


def hero() -> str:
    e = [rect(0,0,1440,720,NAVY),
         rect(64,50,5,60,CYAN,2),
         text(88,79,"Who governs AI-agent interoperability?",42,INK,700),
         text(88,113,"Two standards · one infrastructure problem · different routes to binding decisions",19,MUTED),
         rect(64,151,624,239,PANEL,16,STROKE), rect(752,151,624,239,PANEL,16,STROKE),
         text(92,194,"ERC-8004",27,CYAN,700),
         text(92,222,"Open Ethereum standards process",17,MUTED),
         text(780,194,"Agent2Agent (A2A)",27,GREEN,700),
         text(780,222,"Open contributions, chartered TSC authority",17,MUTED)]
    for x,labels,color,icons in [
        (92,["Proposal","Public review","Separate deployment"],CYAN,[icon_document,icon_review,icon_network]),
        (780,["Contribution","GitVote process","Eight TSC seats"],GREEN,[icon_document,icon_review,icon_network])]:
        xs=[x,x+185,x+370]
        for j,(xx,label,icon) in enumerate(zip(xs,labels,icons)):
            e += [icon(xx+11,260,color), text(xx,335,label,16,INK,600)]
            if j<2:
                e += [line(xx+72,282,xx+164,282,color,2,'marker-end="url(#arrow)"')]
    e += ['<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" '
          'markerWidth="6" markerHeight="6" orient="auto-start-reverse">'
          '<path d="M0 0 L10 5 L0 10 Z" fill="#6B91A9"/></marker></defs>',
          text(92,370,"Participation is open; protocol deployment is distinct from review.",14,MUTED),
          text(780,370,"Anyone may contribute; initial TSC voting is restricted.",14,MUTED),
          text(64,440,"What the released public records support",25,INK,700)]
    cards=[(64,"PARTICIPATION","High inequality in both networks",CYAN),
           (520,"DELIBERATION","Different discussion emphases",GREEN),
           (976,"OBSERVATION SCALE","Connectivity changes with corpus scope",AMBER)]
    for x,head,body,color in cards:
        e += [rect(x,460,400,92,"#111F34",10,STROKE),rect(x,460,5,92,color,2),
              text(x+21,491,head,15,color,700),text(x+21,525,body,17,INK,600)]
    e += [text(64,602,"Trace each result",20,INK,700)]
    stages=["Source records","Query code","Archived data","Processing code","Result tables","Figures & checks"]
    stage_icons=[icon_document,icon_review,icon_table,icon_network,icon_table,icon_review]
    for i,(label,icon) in enumerate(zip(stages,stage_icons)):
        x=64+i*220
        e += [icon(x+1,622,CYAN if i<3 else GREEN), text(x+52,649,label,15,INK,600)]
        if i<5:e += [line(x+167,641,x+208,641,STROKE,2,'marker-end="url(#arrow)"')]
    e += [text(64,697,"DESCRIPTIVE EVIDENCE  ·  PUBLIC RECORDS ONLY  ·  NO CAUSAL OR HUMAN-LABEL ACCURACY CLAIM",13,AMBER,700)]
    return svg(1440,720,"Governance evidence pathway for ERC-8004 and A2A",
               "ERC-8004 has public proposals and review with separate deployment. A2A permits contributions but initial binding votes are held by an eight-seat Technical Steering Committee. Public records show concentration, different deliberation, and scope-dependent connectivity. The six-stage reproducibility pathway leads from source records to checked figures; the comparison is descriptive.",e)


def read_r1() -> dict[str, tuple[float,float]]:
    with (ROOT/R1).open(newline="",encoding="utf-8") as f:
        return {r["Metric"]:(float(r["ERC-8004"]),float(r["Google A2A (full)"]))
                for r in csv.DictReader(f)
                if r["Metric"] in {"Nodes", "Gini(degree)", "Giant component ratio"}}


def read_r2() -> dict[str, dict[str,str]]:
    with (ROOT/R2).open(newline="",encoding="utf-8") as f:
        return {r["case"]:r for r in csv.DictReader(f)}


def participation() -> str:
    r=read_r1(); e=[rect(0,0,1200,680,NAVY),
      text(70,81,"Participation is concentrated in both public networks",34,INK,700),
      text(70,117,"Degree Gini · higher values indicate more unequal interaction counts",18,MUTED),
      line(398,490,1080,490,MUTED,2)]
    for tick in (0,.25,.5,.75,1):
        x=398+682*tick
        e += [line(x,486,x,497,MUTED,1),text(x,521,f"{tick:.2f}",16,MUTED,anchor="middle")]
    for y,label,val,color,nodes in [
        (254,"ERC-8004",r["Gini(degree)"][0],CYAN,int(r["Nodes"][0])),
        (389,"A2A",r["Gini(degree)"][1],GREEN,int(r["Nodes"][1]))]:
        e += [text(70,y,label,25,INK,700),text(70,y+29,f"{nodes:,} public-network actors",17,MUTED),
              rect(398,y-27,682,48,"#24344C",7),rect(398,y-27,682*val,48,color,7),
              text(398+682*val+13,y+7,f"{val:.3f}",24,INK,700)]
    e += [text(70,590,"Measure: Gini of actor degree in the released R1 co-participation networks.",17,MUTED),
          text(70,619,"Boundary: public interactions do not measure demographic inclusion or private coordination.",17,AMBER)]
    return svg(1200,680,"R1 public-network participation inequality",
               "Degree Gini is 0.804 for ERC-8004 with 67 actors and 0.779 for A2A with 771 actors. These are descriptive network measures from public records.",e)


def connectivity() -> str:
    a=read_r1();b=read_r2()
    panels=[(65,"R1 · single protocol",a["Giant component ratio"][0],a["Giant component ratio"][1],
             "67 ERC / 771 A2A actors"),
            (635,"R2 · expanded corpus",float(b["ERC Agent Cluster (Tier 1+2)"]["giant_component_ratio"]),
             float(b["Google A2A"]["giant_component_ratio"]),"204 ERC / 629 A2A actors")]
    e=[rect(0,0,1200,720,NAVY),text(65,75,"Connectivity depends on what enters the network",33,INK,700),
       text(65,111,"Giant-component ratio · fraction of actors in the largest connected group",17,MUTED)]
    for x,head,erc,a2a,note in panels:
        e += [rect(x,153,500,418,PANEL,15,STROKE),text(x+25,198,head,24,INK,700),
              text(x+25,225,note,16,MUTED)]
        for y,label,v,color in [(319,"ERC-8004",erc,CYAN),(421,"A2A",a2a,GREEN)]:
            e += [text(x+25,y-15,label,19,INK,600),rect(x+25,y,390,33,"#273A54",6),
                  rect(x+25,y,390*v,33,color,6),text(x+25+390*v+9,y+24,f"{v:.3f}",18,INK,700)]
        e += [line(x+25,506,x+415,506,MUTED,1)]
        for tick in (0,.5,1):
            xx=x+25+390*tick;e += [line(xx,501,xx,511,MUTED,1),text(xx,535,f"{tick:.1f}",15,MUTED,anchor="middle")]
    e += [text(65,624,"R2 includes 34 related ERC protocols; the A2A corpus was also re-annotated.",17,MUTED),
          text(65,657,"Different corpus boundaries and network constructions: descriptive scope check, not a causal before/after effect.",16,AMBER)]
    return svg(1200,720,"Scale-dependent connectivity in public governance records",
               "At R1 single-protocol scope, giant-component ratios are 0.328 for ERC-8004 and 0.534 for A2A. In the expanded R2 corpus, they are 0.917 for 34 ERC protocols and 0.285 for re-annotated A2A. The scopes and network constructions differ.",e)


def bootstrap() -> str:
    with (ROOT/BOOT).open(newline="",encoding="utf-8") as f:
        rows=list(csv.DictReader(f))
    labels={"Technical":"Technical","Governance-Principle":"Governance principles",
            "Economic":"Economic","Process":"Process","Off-topic":"Off-topic"}
    lo,hi=-13.0,13.0
    def xx(v:float)->float:return 405+(v-lo)/(hi-lo)*690
    e=[rect(0,0,1200,740,NAVY),
       text(65,72,"Equal-size resampling qualifies the discourse contrast",32,INK,700),
       text(65,108,"A2A minus ERC-8004 · percentage points · 2,000 bootstrap resamples",17,MUTED),
       rect(405,166,690,416,PANEL,12),line(xx(0),166,xx(0),582,AMBER,2),
       text(xx(0),151,"No difference",16,AMBER,anchor="middle")]
    for i,row in enumerate(rows):
        y=209+i*78
        mean=100*float(row["mean_difference_a2a_minus_erc"])
        low=100*float(row["ci95_low"]);high=100*float(row["ci95_high"])
        e += [text(66,y+7,labels[row["argument_type"]],20,INK,600),
              line(xx(low),y,xx(high),y,CYAN,6),line(xx(low),y-11,xx(low),y+11,CYAN,2),
              line(xx(high),y-11,xx(high),y+11,CYAN,2),
              f'<circle cx="{xx(mean):.1f}" cy="{y}" r="8" fill="{GREEN}" '
              f'stroke="{NAVY}" stroke-width="2"/>',
              text(1107,y+6,f"{mean:+.1f}",17,INK,700)]
    e += [line(405,593,1095,593,MUTED,1)]
    for tick in (-10,-5,0,5,10):
        e += [line(xx(tick),589,xx(tick),600,MUTED,1),text(xx(tick),625,f"{tick:+d}",15,MUTED,anchor="middle")]
    e += [text(65,673,"All displayed 95% intervals touch or cross zero; uncertainty is from record resampling only.",17,AMBER),
          text(65,701,"Each resample uses 142 records per case. This does not balance platform maturity or organizational resources.",16,MUTED)]
    return svg(1200,740,"Equal-size bootstrap intervals for argument categories",
               "Point estimates and 95 percent intervals for five A2A minus ERC-8004 argument-type shares. Each bootstrap draws 142 records per case, 2000 times. All intervals include or touch zero.",e)


def build() -> dict[str,str]:
    return {"hero.svg":hero(),"participation-inequality.svg":participation(),
            "scope-connectivity.svg":connectivity(),"argument-bootstrap.svg":bootstrap()}


def manifest(outputs:dict[str,str]) -> str:
    cases={
      "hero.svg":("conceptual",[],"Governance architectures and evidence pipeline; schematic, not a measured effect."),
      "participation-inequality.svg":("descriptive",[R1],"Public-network degree Gini; different actor counts."),
      "scope-connectivity.svg":("descriptive",[R1,R2],"R1 and R2 differ in corpus and network construction; no causal transition."),
      "argument-bootstrap.svg":("descriptive",[BOOT],"Equal-size record resampling; not a matched organizational comparison.")}
    entries=[]
    for name,content in outputs.items():
        klass,inputs,boundary=cases[name]
        entries.append({"file":name,"caption_evidence_class":klass,
                        "reader_task":"framing" if name=="hero.svg" else "evidence",
                        "source_code":"scripts/visualise/build_release_figures.py",
                        "inputs":[{"path":str(p),"sha256":sha(ROOT/p)} for p in inputs],
                        "svg_sha256":hashlib.sha256(content.encode("utf-8")).hexdigest(),
                        "alt_text":({"hero.svg":"Comparison of ERC-8004 and A2A authority paths, three descriptive evidence themes, and a six-stage reproducibility pathway.",
                                     "participation-inequality.svg":"Two bars show R1 public-network degree Gini: ERC-8004 0.804 and A2A 0.779.",
                                     "scope-connectivity.svg":"Separate R1 and R2 panels show different giant-component ratios for ERC and A2A under different corpus boundaries.",
                                     "argument-bootstrap.svg":"Five point estimates and 95 percent bootstrap intervals for A2A minus ERC-8004 argument shares; all intervals touch or cross zero."}[name]),
                        "interpretation_boundary":boundary})
    return json.dumps({"schema_version":1,"command":"python3 scripts/visualise/build_release_figures.py",
                       "palette":{"background":NAVY,"ink":INK,"ERC":CYAN,"A2A":GREEN,"boundary":AMBER},
                       "graphics_inventory":{"document":"source and proposals","magnifier":"review and checking",
                                             "network":"interactions and deployment","table":"archived and result data"},
                       "figures":entries},indent=2,ensure_ascii=False)+"\n"


def main() -> int:
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check",action="store_true",help="Compare with checked-in SVGs and manifest")
    args=parser.parse_args()
    outputs=build();outputs["manifest.json"]=manifest(outputs)
    if args.check:
        drift=[name for name,content in outputs.items() if not (OUT/name).is_file() or
               (OUT/name).read_text(encoding="utf-8")!=content]
        if drift:raise SystemExit("Figure release drift: "+", ".join(drift))
        print("PASS: four vector assets and their provenance manifest match tracked tables")
        return 0
    OUT.mkdir(parents=True,exist_ok=True)
    for name,content in outputs.items():(OUT/name).write_text(content,encoding="utf-8")
    print("Built:",", ".join(outputs))
    return 0


if __name__=="__main__":raise SystemExit(main())
